name: Quality Assurance
on: [workflow_call, push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - uses: gradle/gradle-build-action@v3
      - run: ./gradlew test
